#ifndef SCREENGRABCORE_GLOBAL_H
#define SCREENGRABCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCREENGRABCORE_LIBRARY)
#  define SCREENGRABCORE_EXPORT Q_DECL_EXPORT
#else
#  define SCREENGRABCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // SCREENGRABCORE_GLOBAL_H
